### ISSUE TITLE
Confidence Estimates are not Saved

### ISSUE THREAD

**Issue by john19950730** [CS2103AUG2017-F10-B1/main#122] opened 2017-11-03 07:22 UTC
Confidence Estimates are not saved between executions, even though relationships between persons are.

![betweenexecutions](https://user-images.githubusercontent.com/17763037/32363521-beb72dda-c0aa-11e7-8440-a92ea5831a1b.png)

**Comment by Xenonym** [comment] 2017-11-03 08:51
Duplicate of #113

**Closed as completed by Xenonym** 2017-11-03 08:51 UTC
Labels: type.alreadyfixed
