### ISSUE TITLE
Command auto selection will bring problem

### ISSUE THREAD

**Issue by LuLechuan** [CS2103AUG2017-F10-B1/main#121] opened 2017-11-03 07:21 UTC
When I want to use the "history" command, I typed "history". But at this time, "clearHistory" suggestion shown and if i press Enter now, my command will become "clearHistory" which is not I intended to have.
![image](https://user-images.githubusercontent.com/28507005/32363408-39c861d4-c0aa-11e7-8d8f-74f154750069.png)
Although I can still use "history" command by not typing the full name for "history" or click my mouse, but perhaps you can change it to be more convenient by setting that even if i type full "history", both "history and "clearHistory" show up instead of merely the "clearHistory".

**Comment by joanneong** [comment] 2017-11-03 08:40
We have noticed this error, and are in the process of working on it. Thanks for your feedback!

**Comment by Xenonym** [comment] 2017-11-03 08:54
Duplicate of #115

**Closed as completed by Xenonym** 2017-11-03 08:54 UTC
