### ISSUE TITLE
Duplicate colourtag value

### ISSUE THREAD

**Issue by kengying** [CS2103AUG2017-F10-B1/main#118] opened 2017-11-03 07:10 UTC
Steps
1. colourtag friends red
2. colourtag classmates red
![image](https://user-images.githubusercontent.com/28557804/32363181-f1b1e1fa-c0a8-11e7-8450-1d814a4384a1.png)

**Comment by john19950730** [comment] 2017-11-03 07:29
I am not entirely sure how this is a bug. Personally I find that it's fine to have the same colour for different tags.

**Comment by joanneong** [comment] 2017-11-03 08:29
This is particularly so since the colour for the tags is actually decided by the user, and the user might have their own rationale for assigning such colors. For example, I may want to set similar tags such as `acquaintance` and `friend` to the color green, so that when I casually scroll through `Intelli` I can just get a sense of how many "friendlies" there are in general.

**Comment by Xenonym** [comment] 2017-11-03 09:00
Closing as having the same colour for multiple tags is intended behavior; not a bug,

**Closed as completed by Xenonym** 2017-11-03 09:00 UTC
Labels: type.notbug
